version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/applications-tracker
    overwrite: true
file_exists_behavior: OVERWRITE

hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 300
