version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/nextjs-app
    overwrite: true
file_exists_behavior: OVERWRITE

permissions:
  - object: scripts
    pattern: "**"
    mode: 755
    type:
      - file
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300

  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 60
